### ISSUE TITLE
两个小反馈。

### ISSUE THREAD

**Issue by hply** [bestTao/CoordinatorMenu#1]
1.main视图中，如果有viewPager，右滑会冲突，建议博主在CoordinatorMenu的getChildAt(1)的View换成写一个自定义ViewGroup处理收拾；

2.展开菜单的时候，对右侧阴影部分点击— —如果点击的主视图中控件恰好自身有点击事件，不会关闭菜单。我的做法还是在1的建议中对自定义的MainView重写onTouch事件，if (cm.isOpened()) {
            if (event.getAction() == MotionEvent.ACTION_UP) {
                cm.closeMenu();
            }
            return true;
        }

其中cm是CoordinatorMenu的对象，在您的onFinishInflate方法的时候设置一下初始化。
        mMainView = (MainView) getChildAt(1);
        mMainView.setCoordinatorMenu(this);

**Comment by qiantao94** [comment]
谢谢你的反馈，我会花时间研究下这两个问题。

**Comment by qiantao94** [comment]
@HPLY
1. 我试了下，ViewPager右滑没有冲突，可以滑到最后，但是左滑冲突，不能滑到上一个视图，如果改进，只能牺牲菜单滑动打开的范围或者让ViewPager左滑到第一页后才可以滑动打开菜单。这样的话，滑动菜单就涉及到具体应用了，所以不打算更改了。QQ的侧滑可能也考虑到会冲突，所以就没有使用ViewPager
2. 对于阴影点击关闭菜单，我采纳了您的建议，代码已更新。

**Comment by hply** [comment]
嗯嗯，我指的右滑就是手势右滑。。。确实如你所说，我尝试的做法也是针对特定情况，我测试您代码MainView里用了ViewPager+TabLayout,然后重写ViewPager的onTouchEvent方法，然后判断this.getCurrentItem()是否等于0，然后用requestDisallowInterceptTouchEvent来请求是否要请求拦截事件。。。

**Comment by qiantao94** [comment]
哈哈，我的脑子里已经形成了右滑是在屏幕右边滑，滑到左边的刻板印象了，总改不掉。原来还有requestDisallowInterceptTouchEvent这个好方法，感谢分享
